import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

def traducir(column):
   
    traductor = {
    'CÓDIGO ÓRGÃO SUPERIOR': 'código del órgano superior',
    'NOME ÓRGÃO SUPERIOR': 'nombre del órgano superior',
    'CÓDIGO ÓRGÃO': 'código del órgano',
    'NOME ÓRGÃO': 'nombre del órgano',
    'CÓDIGO UNIDADE GESTORA': 'código de la unidad gestora',
    'NOME UNIDADE GESTORA': 'nombre de la unidad gestora',
    'CATEGORIA ECONÔMICA': 'categoría económica',
    'ORIGEM RECEITA': 'origen de los ingresos',
    'ESPÉCIE RECEITA': 'tipo de ingresos',
    'DETALHAMENTO': 'detalle',
    'VALOR PREVISTO ATUALIZADO': 'valor previsto actualizado',
    'VALOR LANÇADO': 'valor registrado',
    'VALOR REALIZADO': 'valor ejecutado',
    'PERCENTUAL REALIZADO': 'porcentaje ejecutado',
    'DATA LANÇAMENTO': 'fecha de registro',
    'ANO EXERCÍCIO': 'año fiscal'
    }
    traducida = traductor[column]
    rename_columna = {column : traducida}
    return rename_columna

def fill_year(df,year):
    df["año fiscal"].replace(np.nan,year,inplace=True)
    return

def year_to_int(df):
    df["año fiscal"] = df["año fiscal"].astype(int)
    return

def date_to_datetime(df):
    df["fecha de registro"]= pd.to_datetime(df["fecha de registro"],errors="coerce")
    return

def numeric_conversion(df):
    df['valor previsto actualizado'] = pd.to_numeric(df['valor previsto actualizado'].str.replace(',', '.'), errors='coerce')
    df['valor registrado'] = pd.to_numeric(df['valor registrado'].str.replace(',', '.'), errors='coerce')
    df['valor ejecutado'] = pd.to_numeric(df['valor ejecutado'].str.replace(',', '.'), errors='coerce')
    df['porcentaje ejecutado'] = pd.to_numeric(df['porcentaje ejecutado'].str.replace(',', '.'), errors='coerce')
    return

def numeric_conversion(df):
    """
    Convierte las columnas de valores monetarios y porcentaje a formato numérico en un DataFrame.
    Reemplaza las comas por puntos para los decimales y maneja valores no convertibles.

    La función convierte las columnas "valor previsto actualizado", "valor registrado", 
    "valor ejecutado" y "porcentaje ejecutado" a formato numérico (float). 
    Multiplica el "porcentaje ejecutado" por 100 para normalizarlo en una escala de 0 a 100.

    Args:
        df (pd.DataFrame): El DataFrame que contiene los datos a procesar.

    Returns:
        pd.DataFrame: El DataFrame con las columnas especificadas convertidas a formato numérico.
                      Si la conversión falla para algún valor, se reemplaza con NaN.
    """
    df['valor previsto actualizado'] = pd.to_numeric(df['valor previsto actualizado'].str.replace(',', '.'), errors='coerce')
    df['valor registrado'] = pd.to_numeric(df['valor registrado'].str.replace(',', '.'), errors='coerce')
    df['valor ejecutado'] = pd.to_numeric(df['valor ejecutado'].str.replace(',', '.'), errors='coerce')
    df['porcentaje ejecutado'] = pd.to_numeric(df['porcentaje ejecutado'].str.replace(',', '.'), errors='coerce')
    df['porcentaje ejecutado'] *= 100
    return

def fill_organo_superior(df):
    """
    Rellena los valores nulos en la columna 'nombre del órgano superior' basándose en la correspondencia con 
    la columna 'código del órgano superior', utilizando un diccionario de mapeo predefinido.

    La función utiliza un diccionario que contiene la correspondencia entre los códigos únicos de 'código del órgano superior'
    y sus respectivos nombres ('nombre del órgano superior'). Luego, se rellenan los valores nulos en 
    'nombre del órgano superior' utilizando el valor correspondiente del diccionario.

    Args:
        df (pd.DataFrame): DataFrame con los datos a procesar. Debe contener las columnas 
                           'código del órgano superior' y 'nombre del órgano superior'.

    Returns:
        None: La función modifica el DataFrame original directamente.
    """

    codigos_organo_superior = { 
        20000: 'Presidência da República',
        22000: 'Ministério da Agricultura, Pecuária e Abastec',
        24000: 'Ministério da Ciência, Tecnologia, Inovações ',
        25000: 'Ministério da Economia',
        26000: 'Ministério da Educação',
        30000: 'Ministério da Justiça e Segurança Pública',
        32000: 'Ministério de Minas e Energia',
        33000: 'Ministério da Previdência Social',
        35000: 'Ministério das Relações Exteriores',
        36000: 'Ministério da Saúde',
        37000: 'Controladoria-Geral da União',
        38000: 'Ministério do Trabalho e Emprego',
        39000: 'Ministério da Infraestrutura',
        41000: 'Ministério das Comunicações',
        44000: 'Ministério do Meio Ambiente',
        49000: 'Ministério do Desenvolvimento Agrário',
        51000: 'Ministério do Esporte',
        52000: 'Ministério da Defesa',
        53000: 'Ministério do Desenvolvimento Regional',
        54000: 'Ministério do Turismo',
        55000: 'Ministério da Cidadania',
        57000: 'Ministério das Mulheres, Igualdade Racial, da',
        58000: 'Ministério da Pesca e Aquicultura',
        63000: 'Advocacia-Geral da União',
        81000: 'Ministério da Mulher, Família e Direitos Huma'
    }
    #Reemplazamos los valores nulos por el valor correcto
    df["nombre del órgano superior"].fillna(df["código del órgano superior"].map(codigos_organo_superior), inplace=True)

    # Invertimos el diccionario para mapear nombres a códigos 
    diccionario_inverso = {valor: clave for clave, valor in codigos_organo_superior.items()} 
    #Básicamente cogemos el valor y la clave y lo volvemos clave -> valor y valor -> clave así podemos hacer la tarea a la inversa

    # Rellenamos los valores nulos en 'código del órgano superior' usando el nombre
    df["código del órgano superior"].fillna(df["nombre del órgano superior"].map(diccionario_inverso), inplace=True)
    return


def fill_sub_organos(df):

    diccionario_organos = {
        20101.0: 'Presidência da República',
        20116.0: 'Fundo de Imprensa Nacional',
        20117.0: 'Fundo Nacional Antidrogas',
        20122.0: 'Secretaria Nacional de Políticas para Mulheres',
        20202.0: 'Fundação Escola Nacional de Administração Pública',
        20203.0: 'Agência Nacional do Cinema',
        20301.0: 'Comissão Nacional de Energia Nuclear',
        20302.0: 'Nuclebrás Equipamentos Pesados S.A.',
        20303.0: 'Indústrias Nucleares do Brasil',
        20402.0: 'Agência Espacial Brasileira',
        20403.0: 'Fundação Casa de Rui Barbosa',
        20404.0: 'Fundação Biblioteca Nacional',
        20408.0: 'Fundação Cultural Palmares',
        20411.0: 'Instituto do Patrimônio Histórico e Artístico Nacional',
        20412.0: 'Fundação Nacional de Artes',
        20415.0: 'Empresa Brasil de Comunicação',
        20501.0: 'Conselho Nacional de Desenvolvimento Científico e Tecnológico',
        20502.0: 'Financiadora de Estudos e Projetos',
        20603.0: 'Superintendência da Zona Franca de Manaus',
        20604.0: 'Instituto Brasileiro de Turismo',
        20605.0: 'Companhia de Desenvolvimento de Barcarena',
        20701.0: 'Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis',
        20924.0: 'Fundo Nacional de Desenvolvimento',
        22000.0: 'Ministério da Agricultura, Pecuária e Abastecimento - Unidades com vínculo direto',
        22201.0: 'Instituto Nacional de Colonização e Reforma Agrária',
        22202.0: 'Empresa Brasileira de Pesquisa Agropecuária',
        22203.0: 'Companhia de Desenvolvimento dos Vales do São Francisco e do Parnaíba',
        22204.0: 'Departamento Nacional de Obras Contra as Secas',
        22211.0: 'Companhia Nacional de Abastecimento',
        22500.0: 'Companhia de Entrepostos e Armazéns Gerais de São Paulo',
        22905.0: 'Fundo de Defesa da Economia Cafeeira',
        24000.0: 'Ministério da Ciência, Tecnologia, Inovações e Comunicações - Unidades com vínculo direto',
        24208.0: 'Instituto Nacional de Tecnologia da Informação',
        24209.0: 'Centro Nacional de Tecnologia Eletrônica Avançada S.A.',
        24901.0: 'Fundo Nacional de Desenvolvimento Científico e Tecnológico',
        25000.0: 'Ministério da Economia - Unidades com vínculo direto',
        25201.0: 'Banco Central do Brasil - Orçamento Fiscal e Seguridade Social',
        25203.0: 'Comissão de Valores Mobiliários',
        25205.0: 'Fundação Instituto Brasileiro de Geografia e Estatística',
        25207.0: 'Serviço Federal de Processamento de Dados',
        25208.0: 'Superintendência de Seguros Privados',
        25211.0: 'Casa da Moeda do Brasil',
        25901.0: 'Fundo de Compensação de Variações Salariais',
        25904.0: 'Fundo de Estabilidade do Seguro Rural',
        25905.0: 'Fundo de Apoio ao Desenvolvimento Social',
        25914.0: 'Fundo de Garantia à Exportação',
        25915.0: 'Fundo Constitucional do Distrito Federal',
        25916.0: 'Fundo Contingente da Extinta RFFSA-FCMP',
        26000.0: 'Ministério da Educação - Unidades com vínculo direto',
        26201.0: 'Colégio Pedro II',
        26230.0: 'Fundação Universidade Federal do Vale do São Francisco',
        26231.0: 'Universidade Federal de Alagoas',
        26232.0: 'Universidade Federal da Bahia',
        26233.0: 'Universidade Federal do Ceará',
        26234.0: 'Universidade Federal do Espírito Santo',
        26235.0: 'Universidade Federal de Goiás',
        26236.0: 'Universidade Federal Fluminense',
        26237.0: 'Universidade Federal de Juiz de Fora',
        26238.0: 'Universidade Federal de Minas Gerais',
        26239.0: 'Universidade Federal do Pará',
        26240.0: 'Universidade Federal da Paraíba',
        26241.0: 'Universidade Federal do Paraná',
        26242.0: 'Universidade Federal de Pernambuco',
        26243.0: 'Universidade Federal do Rio Grande do Norte',
        26244.0: 'Universidade Federal do Rio Grande do Sul',
        26245.0: 'Universidade Federal do Rio de Janeiro',
        26246.0: 'Universidade Federal de Santa Catarina',
        26247.0: 'Universidade Federal de Santa Maria',
        26248.0: 'Universidade Federal Rural de Pernambuco',
        26249.0: 'Universidade Federal Rural do Rio de Janeiro',
        26250.0: 'Universidade Federal de Roraima',
        26251.0: 'Fundação Universidade Federal do Tocantins',
        26252.0: 'Universidade Federal de Campina Grande',
        26253.0: 'Universidade Federal Rural da Amazônia',
        26254.0: 'Universidade Federal do Triângulo Mineiro',
        26255.0: 'Universidade Federal dos Vales do Jequitinhonha e Mucuri',
        26256.0: 'Centro Federal de Educação Tecnológica Celso Suckow da Fonseca',
        26257.0: 'Centro Federal de Educação Tecnológica de Minas Gerais',
        26258.0: 'Universidade Tecnológica Federal do Paraná',
        26260.0: 'Universidade Federal de Alfenas',
        26261.0: 'Universidade Federal de Itajubá',
        26262.0: 'Universidade Federal de São Paulo',
        26263.0: 'Universidade Federal de Lavras',
        26264.0: 'Universidade Federal Rural do Semi-Árido',
        26266.0: 'Fundação Universidade Federal do Pampa',
        26267.0: 'Universidade Federal da Integração Latino-Americana',
        26268.0: 'Fundação Universidade Federal de Rondônia',
        26269.0: 'Universidade Federal do Estado do Rio de Janeiro',
        26270.0: 'Fundação Universidade do Amazonas',
        26271.0: 'Fundação Universidade de Brasília',
        26272.0: 'Fundação Universidade do Maranhão',
        26273.0: 'Universidade Federal do Rio Grande',
        26274.0: 'Fundação Universidade Federal de Uberlândia',
        26275.0: 'Fundação Universidade Federal do Acre',
        26276.0: 'Fundação Universidade Federal do Mato Grosso',
        26277.0: 'Universidade Federal de Ouro Preto',
        26278.0: 'Fundação Universidade Federal de Pelotas',
        26279.0: 'Fundação Universidade Federal do Piauí',
        26280.0: 'Fundação Universidade Federal de São Carlos',
        26281.0: 'Fundação Universidade Federal de Sergipe',
        26282.0: 'Universidade Federal de Viçosa',
        26283.0: 'Fundação Universidade Federal do Mato Grosso do Sul',
        26284.0: 'Fundação Universidade Federal de Ciências da Saúde de Porto Alegre',
        26285.0: 'Fundação Universidade Federal de São João Del-Rei',
        26286.0: 'Fundação Universidade Federal do Amapá',
        26290.0: 'Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira',
        26291.0: 'Fundação Coordenação de Aperfeiçoamento de Pessoal de Nível Superior',
        26292.0: 'Fundação Joaquim Nabuco',
        26294.0: 'Hospital de Clínicas de Porto Alegre',
        26298.0: 'Fundo Nacional de Desenvolvimento da Educação',
        26350.0: 'Fundação Universidade Federal da Grande Dourados',
        26351.0: 'Universidade Federal do Recôncavo da Bahia',
        26352.0: 'Fundação Universidade Federal do ABC',
        26402.0: 'Instituto Federal de Alagoas',
        26403.0: 'Instituto Federal do Amazonas',
        26404.0: 'Instituto Federal Baiano',
        26405.0: 'Instituto Federal do Ceará',
        26406.0: 'Instituto Federal do Espírito Santo',
        26407.0: 'Instituto Federal Goiano',
        26408.0: 'Instituto Federal do Maranhão',
        26409.0: 'Instituto Federal de Minas Gerais',
        26410.0: 'Instituto Federal do Norte de Minas Gerais',
        26411.0: 'Instituto Federal do Sudeste de Minas Gerais',
        26412.0: 'Instituto Federal do Sul de Minas Gerais',
        26413.0: 'Instituto Federal do Triângulo Mineiro',
        26414.0: 'Instituto Federal do Mato Grosso',
        26415.0: 'Instituto Federal do Mato Grosso do Sul',
        26416.0: 'Instituto Federal do Pará',
        26417.0: 'Instituto Federal da Paraíba',
        26418.0: 'Instituto Federal de Pernambuco',
        26419.0: 'Instituto Federal do Rio Grande do Sul',
        26420.0: 'Instituto Federal Farroupilha',
        26421.0: 'Instituto Federal de Rondônia',
        26422.0: 'Instituto Federal Catarinense',
        26423.0: 'Instituto Federal de Sergipe',
        26424.0: 'Instituto Federal do Tocantins',
        26425.0: 'Instituto Federal do Acre',
        26426.0: 'Instituto Federal do Amapá',
        26427.0: 'Instituto Federal da Bahia',
        26428.0: 'Instituto Federal de Brasília',
        26429.0: 'Instituto Federal de Educação, Ciência e Tecnologia de Goiás',
        26430.0: 'Instituto Federal do Sertão de Pernambuco',
        26431.0: 'Instituto Federal do Piauí',
        26432.0: 'Instituto Federal do Paraná',
        26433.0: 'Instituto Federal do Rio de Janeiro',
        26434.0: 'Instituto Federal Fluminense',
        26435.0: 'Instituto Federal do Rio Grande do Norte',
        26436.0: 'Instituto Federal Sul-rio-grandense',
        26437.0: 'Instituto Federal de Roraima',
        26438.0: 'Instituto Federal de Santa Catarina',
        26439.0: 'Instituto Federal de São Paulo',
        26440.0: 'Universidade Federal da Fronteira Sul',
        26441.0: 'Universidade Federal do Oeste do Pará',
        26442.0: 'Universidade da Integração Internacional da Lusofonia Afro-Brasileira',
        26443.0: 'Empresa Brasileira de Serviços Hospitalares',
        26447.0: 'Universidade Federal do Oeste da Bahia',
        26448.0: 'Universidade Federal do Sul e Sudeste do Pará',
        26449.0: 'Universidade Federal do Cariri',
        26450.0: 'Universidade Federal do Sul da Bahia',
        28500.0: 'Fundo de Garantia para a Promoção da Competitividade',
        29201.0: 'Departamento Nacional de Estradas de Rodagem',
        29205.0: 'Empresa de Trens Urbanos de Porto Alegre',
        29208.0: 'Companhia de Pesquisa de Recursos Minerais',
        29209.0: 'VALEC Engenharia, Construções e Ferrovias S.A.',
        29214.0: 'Companhia Brasileira de Trens Urbanos',
        30000.0: 'Ministério da Justiça e Segurança Pública - Unidades com vínculo direto',
        30108.0: 'Departamento de Polícia Federal',
        30202.0: 'Fundação Nacional do Índio',
        30203.0: 'Instituto Nacional de Metrologia, Qualidade e Tecnologia',
        30204.0: 'Instituto Nacional da Propriedade Industrial',
        30205.0: 'Fundação Nacional do Índio - Patrimônio Indígena',
        30211.0: 'Conselho Administrativo de Defesa Econômica',
        30802.0: 'Departamento de Polícia Rodoviária Federal',
        30905.0: 'Secretaria Nacional do Consumidor Fundo',
        30907.0: 'Fundo Penitenciário Nacional',
        30911.0: 'Fundo Nacional de Segurança Pública',
        30912.0: 'Fundo Nacional Antidrogas',
        31280.0: 'Caixa de Construções de Casas para o Pessoal da Marinha do Brasil',
        32000.0: 'Ministério de Minas e Energia - Unidades com vínculo direto',
        32205.0: 'Agência Nacional do Petróleo, Gás Natural e Biocombustíveis',
        32210.0: 'Agência Nacional de Energia Elétrica',
        32263.0: 'Departamento Nacional de Produção Mineral',
        32314.0: 'Empresa de Pesquisa Energética',
        33000.0: 'Ministério da Previdência Social - Unidades com vínculo direto',
        33206.0: 'Superintendência Nacional de Previdência Complementar',
        34902.0: 'Fundo Nacional de Cultura',
        35000.0: 'Ministério das Relações Exteriores - Unidades com vínculo direto',
        35201.0: 'Fundação Alexandre de Gusmão',
        36000.0: 'Ministério da Saúde - Unidades com vínculo direto',
        36201.0: 'Fundação Oswaldo Cruz',
        36210.0: 'Hospital Nossa Senhora da Conceição S.A.',
        36211.0: 'Fundação Nacional de Saúde',
        36212.0: 'Agência Nacional de Vigilância Sanitária',
        36213.0: 'Agência Nacional de Saúde Suplementar',
        37201.0: 'Fundação Jorge Duprat Figueiredo, de Segurança e Medicina do Trabalho',
        37202.0: 'Instituto Nacional do Seguro Social',
        37904.0: 'Fundo do Regime Geral da Previdência Social',
        38000.0: 'Ministério do Trabalho e Emprego - Unidades com vínculo direto',
        38901.0: 'Fundo de Amparo ao Trabalhador',
        39000.0: 'Ministério da Infraestrutura - Unidades com vínculo direto',
        39250.0: 'Agência Nacional de Transportes Terrestres',
        39252.0: 'Departamento Nacional de Infraestrutura de Transportes',
        39253.0: 'Empresa de Planejamento e Logística S.A.',
        39811.0: 'Companhia Docas do Rio de Janeiro',
        39812.0: 'Companhia Docas do Estado da Bahia',
        39813.0: 'Companhia Docas do Ceará',
        39814.0: 'Companhia Docas do Pará',
        39816.0: 'Companhia Docas do Estado de São Paulo',
        39817.0: 'Companhia Docas do Espírito Santo',
        41000.0: 'Ministério das Comunicações - Unidades com vínculo direto',
        41231.0: 'Agêncial Nacional de Telecomunicações',
        41232.0: 'Fundo de Universalização dos Serviços de Telecomunicações',
        41903.0: 'Fundo para o Desenvolvimento Tecnológico das Telecomunicações',
        42207.0: 'Instituto Brasileiro de Museus',
        44000.0: 'Ministério do Meio Ambiente - Unidades com vínculo direto',
        44204.0: 'Fundo Nacional do Meio Ambiente',
        44205.0: 'Agência Nacional de Águas',
        44206.0: 'Instituto de Pesquisas Jardim Botânico do Rio de Janeiro',
        44207.0: 'Instituto Chico Mendes de Conservação da Biodiversidade',
        44208.0: 'Serviço Florestal Brasileiro',
        44902.0: 'Fundo Nacional sobre Mudança no Clima',
        49000.0: 'Ministério do Desenvolvimento Agrário - Unidades com vínculo direto',
        49001.0: 'Fundo de Terras e da Reforma Agrária',
        49280.0: 'Empresa Brasileira de Correios e Telégrafos',
        49901.0: 'Departamento do Fundo da Marinha Mercante',
        52000.0: 'Ministério da Defesa - Unidades com vínculo direto',
        52111.0: 'Comando da Aeronáutica',
        52121.0: 'Comando do Exército',
        52131.0: 'Comando da Marinha',
        52132.0: 'Comando da Marinha - Fundo Naval',
        52133.0: 'Fundo de Desenvolvimento do Ensino Profissional Marítimo',
        52211.0: 'Caixa de Financiamento Imobiliário da Aeronáutica',
        52221.0: 'Indústria de Material Bélico do Brasil',
        52222.0: 'Fundação Osório',
        52904.0: 'Fundo do Exército',
        52911.0: 'Fundo Aeronáutico',
        53000.0: 'Ministério do Desenvolvimento Regional - Unidades com vínculo direto',
        53202.0: 'Superintendência do Desenvolvimento da Amazônia',
        53203.0: 'Superintendência do Desenvolvimento do Nordeste',
        53207.0: 'Superintendência de Desenvolvimento do Centro-Oeste',
        53901.0: 'Fundo Constitucional de Financiamento do Norte',
        53902.0: 'Fundo Constitucional de Financiamento do Centro-Oeste',
        53903.0: 'Fundo Constitucional de Financiamento do Nordeste',
        54000.0: 'Ministério do Turismo - Unidades com vínculo direto',
        54901.0: 'Fundo Geral de Turismo',
        55000.0: 'Ministério da Cidadania - Unidades com vínculo direto',
        55001.0: 'Fundo Nacional de Assistência Social',
        56901.0: 'Fundo Nacional de Segurança e Educação de Trânsito',
        56902.0: 'Fundo Nacional de Habitação de Interesse Social',
        58000.0: 'Ministério da Pesca e Aquicultura - Unidades com vínculo direto',
        60000.0: 'Gabinete da Vice-Presidência da República',
        61000.0: 'Secretaria de Assuntos Estratégicos',
        61201.0: 'Instituto de Pesquisa Econômica Aplicada',
        62000.0: 'Secretaria de Aviação Civil',
        62201.0: 'Agência Nacional de Aviação Civil',
        62901.0: 'Fundo Nacional de Aviação Civil',
        63000.0: 'Advocacia-Geral da União - Unidades com vínculo direto',
        64000.0: 'Secretaria de Direitos Humanos',
        64901.0: 'Fundo Nacional para a Criança e o Adolescente',
        64902.0: 'Fundo Nacional do Idoso',
        66000.0: 'Controladoria-Geral da União',
        67000.0: 'Secretaria de Políticas de Promoção da Igualdade Racial',
        68000.0: 'Secretaria de Portos',
        68201.0: 'Agência Nacional de Transportes Aquaviários',
        69000.0: 'Secretaria da Micro e Pequena Empresa',
        71902.0: 'Fundo Soberano do Brasil',
        74917.0: 'Fundo de Desenvolvimento da Amazônia',
        74918.0: 'Fundo de Desenvolvimento do Nordeste',
        74919.0: 'Fundo de Desenvolvimento do Centro-Oeste',
        90000.0: 'Reserva de Contingência',
        91214.0: 'Autoridade Pública Olímpica'
    }
        
    #Reemplazamos los valores nulos por el valor correcto
    df["nombre del órgano"].fillna(df["código del órgano"].map(diccionario_organos), inplace=True)

    # Invertimos el diccionario para mapear nombres a códigos 
    diccionario_inverso_organos = {valor: clave for clave, valor in diccionario_organos.items()} 
    #Básicamente cogemos el valor y la clave y lo volvemos clave -> valor y valor -> clave así podemos hacer la tarea a la inversa

    # Rellenamos los valores nulos en 'código del órgano superior' usando el nombre
    df["código del órgano"].fillna(df["nombre del órgano"].map(diccionario_inverso_organos), inplace=True)

    return

def fill_unidad_gestora(df):
    
    diccionario_unidad_gestora = {
        110005.0: 'SECRETARIA DE ADMINISTRACAO-SET.ORC.E FIN./PR',
        110060.0: 'COORD. GERAL DE ORC. FIN. E ANAL. CONT. - AGU',
        110101.0: 'GABINETE DA VICE-PRESIDENCIA DA REPUBLICA',
        110174.0: 'DIRETORIA DE GESTAO INTERNA/SE/CGU',
        110244.0: 'FUNDO NACIONAL PARA A CRIANCA E O ADOLESCENTE',
        110245.0: 'FUNDO DE IMPRENSA NACIONAL/EXEC.ORC.FINANC.',
        110246.0: 'FUNDO NACIONAL ANTIDROGAS',
        110407.0: 'DEPARTAMENTO DE PLANEJ, ORC E FINANCAS (MD)',
        110591.0: 'FUNDO NACIONAL DE AVIACAO CIVIL',
        110690.0: 'SEC.ESPEC.DE AGRIC.FAMIL.E DO DESENV.AGRARIO',
        113206.0: 'INDUSTRIAS NUCLEARES DO BRASIL S/A - INB',
        113208.0: 'NUCLEBRAS EQUIPAMENTOS PESADOS S/A-NUCLEP',
        113209.0: 'CNEN-ORCAMENTO E FINANCAS',
        113214.0: 'AGENCIA NACIONAL DE AVIACAO CIVIL',
        113601.0: 'INSTITUTO DE PESQUISA ECONOMICA APLICADA',
        113802.0: 'DEPARTAMENTO NAC. DE OBRAS CONTRA AS SECAS/UO',
        114601.0: 'FUNDACAO IBGE-ADMINISTRACAO CENTRAL/RJ',
        114702.0: 'FUNDACAO ESCOLA NACIONAL DE ADM. PUBLICA',
        115406.0: 'EMPRESA BRASIL DE COMUNICACAO S.A',
        120002.0: 'DIRETORIA DE ECON E FINANCAS DA AERONAUTICA',
        120999.0: 'MAER - DIFERENCA CAMBIAL',
        121002.0: 'SECRETARIA DE ECON. E FIN.DA AER.- F.AER.',
        123001.0: 'CAIXA FINANCIAMENTO IMOBILIARIO AERONAUTICA',
        130101.0: 'COORD.-GERAL DE ORCAMENTO E FINANCAS-MAPA',
        130137.0: 'FUNDO DE DEFESA DA ECON.CAFEEIRA/FUNCAFE/SPA',
        135037.0: 'EMBRAPA-SETORIAL',
        135100.0: 'COMPANHIA NACIONAL DE ABASTECIMENTO',
        150014.0: 'SUBSECRETARIA DE PLANEJ. E ORCAMENTO SPO(MEC)',
        153010.0: 'CENTRO FED.DE EDUC.TECNOL.CELSO S.DA FONSECA',
        153015.0: 'CENTRO FEDERAL DE EDUCACAO TECNOLOGICA DE MG',
        153019.0: 'UNIVERSIDADE TECNOLOGICA FEDERAL DO PARANA',
        153028.0: 'UNIVERSIDADE FEDERAL DE ALFENAS',
        153030.0: 'UNIVERSIDADE FEDERAL DE ITAJUBA',
        153031.0: 'UNIFESP-UNIVERSIDADE FEDERAL DE SAO PAULO',
        153032.0: 'UNIVERSIDADE FEDERAL DE LAVRAS',
        153033.0: 'UNIVERSIDADE FEDERAL RURAL DO SEMI-ARIDO - RN',
        153034.0: 'UNIVERSIDADE FEDERAL RURAL DA AMAZONIA',
        153035.0: 'UNIVERSIDADE FEDERAL DO TRIANGULO MINEIRO',
        153036.0: 'UNIVERSIDADE FED.VALES JEQUITINHONHA E MUCURI',
        153037.0: 'UNIVERSIDADE FEDERAL DE ALAGOAS',
        153038.0: 'UNIVERSIDADE FEDERAL DA BAHIA',
        153045.0: 'UNIVERSIDADE FEDERAL DO CEARA',
        153046.0: 'UNIVERSIDADE FEDERAL DO ESPIRITO SANTO',
        153052.0: 'UNIVERSIDADE FEDERAL DE GOIAS',
        153056.0: 'UNIVERSIDADE FEDERAL FLUMINENSE',
        153061.0: 'UNIVERSIDADE FEDERAL DE JUIZ DE FORA',
        153062.0: 'UNIVERSIDADE FEDERAL DE MINAS GERAIS',
        153063.0: 'UNIVERSIDADE FEDERAL DO PARA',
        153065.0: 'UNIVERSIDADE FEDERAL DA PARAIBA',
        153079.0: 'UNIVERSIDADE FEDERAL DO PARANA',
        153080.0: 'UNIVERSIDADE FEDERAL DE PERNAMBUCO',
        153103.0: 'UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE',
        153114.0: 'UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL',
        153115.0: 'UNIVERSIDADE FEDERAL DO RIO DE JANEIRO',
        153163.0: 'UNIVERSIDADE FEDERAL DE SANTA CATARINA',
        153164.0: 'UNIVERSIDADE FEDERAL DE SANTA MARIA',
        153165.0: 'UNIVERSIDADE FEDERAL RURAL DE PERNAMBUCO',
        153166.0: 'UNIVERSIDADE FEDERAL RURAL DO RIO DE JANEIRO',
        153167.0: 'COLEGIO PEDRO II',
        153173.0: 'FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCACAO',
        153978.0: 'INST.NACIONAL DE EST.E PESQUISAS EDUCACIONAIS',
        154003.0: 'FUND.COORD.DE APERF.DE PESSOAL NIVEL SUPERIOR',
        154032.0: 'FUND.UNIV.FED.DE.CIENC.DA SAUDE DE P.ALEGRE',
        154034.0: 'UNIRIO UNIVERSIDADE FEDERAL DO ESTADO RJ',
        154039.0: 'FUNDACAO UNIVERSIDADE DO AMAZONAS',
        154040.0: 'FUNDACAO UNIVERSIDADE DE BRASILIA - FUB',
        154041.0: 'FUNDACAO UNIVERSIDADE DO MARANHAO',
        154042.0: 'UNIVERSIDADE FEDERAL DO RIO GRANDE - FURG',
        154043.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE UBERLANDIA',
        154044.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO ACRE',
        154045.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE MATO GROSSO',
        154046.0: 'UNIVERSIDADE FEDERAL DE OURO PRETO',
        154047.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE PELOTAS',
        154048.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO PIAUI',
        154049.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE SAO CARLOS',
        154050.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE SERGIPE',
        154051.0: 'UNIVERSIDADE FEDERAL DE VICOSA',
        154054.0: 'FUNDACAO UNIVERS.FED. DE MATO GROSSO DO SUL',
        154055.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA',
        154069.0: 'FUNDACAO UNIVERSIDADE FEDERAL DE S.J.DEL-REI',
        154080.0: 'UNIVERSIDADE FEDERAL DE RORAIMA',
        154215.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO AMAPA',
        154359.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO PAMPA',
        154419.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO TOCANTINS',
        154421.0: 'FUND. UNIVERSIDADE FEDERAL VALE SAO FRANCISCO',
        154502.0: 'FUNDACAO UNIVERSIDADE FED. DA GRANDE DOURADOS',
        154503.0: 'FUNDACAO UNIVERSIDADE FEDERAL DO ABC',
        154999.0: 'CAPES - DIFERENCA CAMBIAL',
        155001.0: 'HOSPITAL DE CLINICAS DE PORTO ALEGRE',
        155007.0: 'EMPRESA BRASILEIRA DE SERVICOS HOSPITALARES',
        158009.0: 'INST. FED. DO PARANA/ REITORIA',
        158092.0: 'UNIVERSIDADE FEDERAL DO RECONCAVO DA BAHIA',
        158099.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO TRIA.MINEIRO',
        158121.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO NORTE DE MG',
        158122.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE MINAS GERAIS',
        158123.0: 'INSTITUTO FED CIENCIA TECNOL SUDESTE MG',
        158124.0: 'IF GOIANO',
        158125.0: 'INSTITUTO FEDERAL CATARINENSE - REITORIA',
        158126.0: 'INST.FED.DE EDUC.,CIE.E TEC.SUL-RIO-GRANDENSE',
        158127.0: 'INST.FED.DE EDUC.,CIENC.E TEC.FARROUPILHA',
        158128.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO MARANHAO',
        158129.0: 'INST FED DE EDUC CIENC E TECNOLOGIA BAIANO',
        158131.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO TOCANTINS',
        158132.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO MAT.G.DO SUL',
        158133.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO CEARA',
        158134.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE SERGIPE',
        158135.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO PARA',
        158136.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE PERNAMBUCO',
        158137.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO SUL DE MG',
        158138.0: 'IFPB - REITORIA',
        158139.0: 'INST.FED.DE EDUC.,CIENC.E TEC.FLUMINENSE',
        158141.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO RS',
        158142.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO AMAZONAS',
        158143.0: 'IFB - REITORIA - BRASILIA-DF',
        158144.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO MATO GROSSO',
        158145.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DA BAHIA',
        158146.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI',
        158147.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE ALAGOAS',
        158148.0: 'INST. FED. DE EDUC.,CIENC. E TEC. DE RONDONIA',
        158149.0: 'INST.FED.DE ED.,CIENC.E TEC.DO S.PERNAMBUCANO',
        158150.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO AMAPA',
        158151.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO ESP.SANTO',
        158152.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE RORAIMA',
        158153.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE GOIAS',
        158154.0: 'INSTITUTO FEDERAL DE SAO PAULO',
        158155.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO RN',
        158156.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DO ACRE',
        158157.0: 'REITORIA',
        158195.0: 'UNIVERSIDADE FEDERAL DE CAMPINA GRANDE',
        158515.0: 'UNIVERSIDADE FEDERAL DO OESTE DO PARA',
        158516.0: 'INST.FED.DE EDUC.,CIENC.E TEC.DE STA.CAT/IFSC',
        158517.0: 'UNIVERSIDADE FEDERAL DA FRONTEIRA SUL',
        158565.0: 'UNIV.DA INTEG.INTERN.DA LUSOF.AFRO-BRASILEIRA',
        158658.0: 'UNIV. FEDERAL DA INTEGRACAO LATINO-AMERICANA',
        158717.0: 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA',
        158718.0: 'UNIVERSIDADE FEDERAL DO SUL E SUDESTE DO PARA',
        158719.0: 'UNIVERSIDADE FEDERAL DO CARIRI',
        158720.0: 'UNIVERSIDADE FEDERAL DO SUL DA BAHIA',
        160075.0: 'D CONT - SETORIAL FINANCEIRA',
        164204.0: 'FUNDACAO OSORIO',
        167086.0: 'FUNDO DO EXERCITO',
        168002.0: 'INDUSTRIA DE MATERIAL BELICO DO BRASIL/GESTOR',
        170010.0: 'SECRETARIA DA RECEITA FEDERAL DO BRASIL-RFB',
        170013.0: 'SETORIAL ORCAMENTARIA E FINANCEIRA / ME',
        170026.0: 'PROCURADORIA DA FAZENDA NACIONAL - MA',
        170033.0: 'PROCURADORIA DA FAZENDA NACIONAL - PI',
        170073.0: 'PROCURADORIA DA FAZENDA NACIONAL-SE',
        170076.0: 'PROCURADORIA DA FAZENDA NACIONAL - BA',
        170086.0: 'PROCURADORIA DA FAZENDA NACIONAL - MG',
        170101.0: 'PROCURADORIA DA FAZENDA NACIONAL-ES',
        170107.0: 'PROCURADORIA DA FAZENDA NACIONAL-MS',
        170154.0: 'PROCURADORIA DA FAZENDA NACIONAL-PR',
        170167.0: 'PROCURADORIA DA FAZENDA NACIONAL/SC',
        170196.0: 'PROCURADORIA DA FAZENDA NACI0NAL/GO',
        170204.0: 'PROCURADORIA-REGIONAL DA FAZ.NAC.1A.REGIAO/DF',
        170215.0: 'PROCURADORIA DA FAZENDA NACIONAL/PA',
        170229.0: 'PROCURADORIA DA FAZENDA NACIONAL/MT',
        170230.0: 'PROCURADORIA DA FAZENDA NACIONAL/CE',
        170231.0: 'PROCURADORIA DA FAZENDA NACIONAL/PB',
        170232.0: 'PROCURADORIA DA FAZENDA NACIONAL/AL',
        170233.0: 'PROCURADORIA DA FAZENDA NACIONAL/AM',
        170234.0: 'PROCURADORIA DA FAZENDA NACIONAL/RN',
        170237.0: 'PROCURADORIA DA FAZENDA NACIONAL/AC',
        170238.0: 'PROCURADORIA DA FAZENDA NACIONAL/RR',
        170265.0: 'PROCURADORIA REGIONAL DA F.NACIONAL/4A REGIAO',
        170266.0: 'PROCURADORIA-REGIONAL DA FAZENDA NACIONAL/PE',
        170267.0: 'PROCURADORIA-REGIONAL DA FAZENDA NACIONAL/RJ',
        170268.0: 'PROCURADORIA-REGIONAL DA FAZENDA NACIONAL/SP',
        170285.0: 'PROCURADORIA FAZ.NACIONAL NO EST.TOCANTINS',
        170356.0: 'FUNDO DE GARANTIA A EXPORTACAO-BNDES',
        170357.0: 'PROCURADORIA DA FAZENDA NACIONAL EM RONDONIA',
        170358.0: 'PROCURADORIA DA FAZ.NAC. NO ESTADO DO AMAPA',
        170380.0: 'FUNDO DE APOIO AO DESENVOLVIMENTO SOCIAL',
        170381.0: 'FUNDO DE COMPENSACAO E VARIACAO SALARIAL',
        170392.0: 'FUNDO CONSTITUCIONAL DO DISTRITO FEDERAL',
        170474.0: 'FUNDO SOBERANO DO BRASIL',
        173030.0: 'COMISSAO DE VALORES MOBILIARIOS',
        173039.0: 'SUPERINTENDENCIA DE SEGUROS PRIVADOS - RJ',
        173057.0: 'BANCO CENTRAL DO BRASIL',
        173065.0: 'FUNDO CONTINGENTE DA EXTINTA RFFSA-FC',
        179083.0: 'CASA DA MOEDA DO BRASIL',
        179103.0: 'FUNDO DE ESTABILIDADE DO SEGURO RURAL',
        180077.0: 'SETORIAL ORCAMENTARIA E FINANCEIRA - (ME)',
        183023.0: 'INSTITUTO NAC.DE METROLOG. QUALID. E TECNOLOG',
        183038.0: 'INSTITUTO NACIONAL DA PROPRIEDADE INDUSTRIAL',
        185001.0: 'INSTITUTO BRASILEIRO DE TURISMO - EM EXTINCAO',
        187002.0: 'FUNDO GERAL DE TURISMO-FUNGETUR',
        193028.0: 'SUPERINTENDENCIA DA ZONA FRANCA DE MANAUS/AM',
        193034.0: 'IBAMA - INST.BRASILEIRO MEIO AMBIENTE/MATRIZ',
        193107.0: 'IBAMA - SUPERINTENDENCIA DO ESPIRITO SANTO/ES',
        193112.0: 'IBAMA - SUPERINTENDENCIA MATO GROSSO SUL/MS',
        193120.0: 'IBAMA - SUPERINTENDENCIA RIO GRANDE NORTE/RN',
        193125.0: 'IBAMA - SUPERINTENDENCIA DE SANTA CATARINA/SC',
        193129.0: 'IBAMA - SUPERINTENDENCIA DE SAO PAULO/SP',
        194040.0: 'RENDA DO PATRIMONIO INDIGENA',
        194088.0: 'FUNDACAO NACIONAL DO INDIO - U.O.',
        195006.0: 'CIA DE DES.DOS VALES DO S.FRANC.E DO PARNAIBA',
        200016.0: 'SECRETARIA DE DIREITOS HUMANOS/PR',
        200021.0: 'SECRETARIA DE POLITICAS PARA AS MULHERES',
        200094.0: 'COORDENACAO-GERAL DE ORCAMENTO E FINANCAS-MJ',
        200109.0: 'DEPTO.DE POLICIA RODOVIARIA FEDERAL',
        200246.0: 'FUNDO NACIONAL ANTIDROGAS',
        200320.0: 'FUNDO NACIONAL DE SEG. E EDUCACAO DE TRANSITO',
        200331.0: 'FUNDO NACIONAL DE SEGURANCA PUBLICA - FNSP',
        200333.0: 'DEPEN - DIRETORIA EXECUTIVA',
        200336.0: 'COORDENACAO DE ORCAMENTO FINANCAS CONTABILIDA',
        200401.0: 'FUNDO DE DEFESA DOS DIREITOS DIFUSOS',
        201002.0: 'COORDENACAO-GERAL DE ORC. E FINANCAS/MP',
        201924.0: 'FUNDO NACIONAL DE DESENVOLVIMENTO',
        203001.0: 'AGENCIA ESPACIAL BRASILEIRA/AEB',
        203003.0: 'AGENCIA NACIONAL DO CINEMA',
        207001.0: 'FUNDO NACIONAL DO IDOSO',
        211999.0: 'MARINHA - DIFERENCA CAMBIAL',
        225001.0: 'CIA.DE ENTREPOSTOS E ARMAZENS GER.DE S.PAULO',
        238012.0: 'SECRETARIA DE POLIT. DE PROM.DA IGUALD.RACIAL',
        240005.0: 'COORDENACAO-GERAL DE ORCAMENTO E FINANCAS-MRE',
        240101.0: 'COORDENACAO-GERAL DE RECURSOS LOGISTICOS',
        240102.0: 'COORDENACAO-GERAL DE ORCAMENTO E FINANCAS',
        240901.0: 'FUNDO NAC.DE DESENV. CIENT. E TECNOLOGICO',
        243001.0: 'INSTITUTO NAC.DE TECNOLOGIA DA INFORMACAO ITI',
        244001.0: 'FUNDACAO ALEXANDRE DE GUSMAO',
        245209.0: 'CENTRO NACIONAL DE TECNOLOGIA ELETRONICA AVAN',
        250088.0: 'SPO-COORD.-GERAL DE ORC.E FINANCAS/MS',
        253002.0: 'AGENCIA NACIONAL DE VIGILANCIA SANITARIA',
        253003.0: 'AGENCIA NACIONAL DE SAUDE SUPLEMENTAR',
        254420.0: 'FUNDACAO OSWALDO CRUZ',
        255000.0: 'FUNDACAO NACIONAL DE SAUDE - DF',
        255003.0: 'FUNDACAO NACIONAL DE SAUDE - AP',
        255008.0: 'FUNDACAO NACIONAL DE SAUDE - ES',
        255011.0: 'FUNDACAO NACIONAL DE SAUDE - MT',
        255014.0: 'FUNDACAO NACIONAL DE SAUDE - PA',
        255015.0: 'FUNDACAO NACIONAL DE SAUDE - PB',
        264001.0: 'FUNDACENTRO - FUND.JORGE DUPRAT/CTN/SEDE - SP',
        275060.0: 'EMPRESA DE TRENS URBANOS DE PORTO ALEGRE S/A',
        275068.0: 'CIA BRASILEIRA DE TRENS URBANOS-ADM.CENTRAL',
        275075.0: 'VALEC ENGENHARIA CONSTRUCOES E FERROVIAS S/A.',
        277001.0: 'FUNDO DA MARINHA MERCANTE',
        280102.0: 'COORDENACAO-GERAL DE ORCAM.FINAN.CONTAB/MDIC',
        287001.0: 'FUNDO DE GAR.P/PROMOC.DA COMPETITIVIDADE±FGPC',
        303001.0: 'CONSELHO ADMINISTRATIVO DE DEFESA ECONOMICA',
        307001.0: 'FUNDO NACIONAL PARA A CRIANCA E O ADOLESCENTE',
        307002.0: 'FUNDO NACIONAL DO IDOSO',
        320002.0: 'COORD.GERAL DE ORCAM.E FIN./M.M.E',
        323002.0: 'DEPARTAMENTO NAC. DE PRODUCAO MINERAL - SEDE',
        323028.0: 'AGENCIA NACIONAL DE ENERGIA ELETRICA',
        323030.0: 'AG. NAC.DO PETROLEO GAS NAT.E BIOCOM',
        325001.0: 'EMPRESA DE PESQUISA ENERGETICA',
        330002.0: 'COORDENACAO-GERAL DE ORC. FIN.E CONTABILIDADE',
        330013.0: 'FUNDO NACIONAL DE ASSISTENCIA SOCIAL',
        333001.0: 'COORD.GERAL DE ORC. FIN. E CONTABILIDADE',
        340002.0: 'COORD.GERAL DE PLAN. ORC. FIN. E CONTAB/FNC',
        344001.0: 'FUNDACAO CASA DE RUI BARBOSA',
        344002.0: 'FUNDACAO JOAQUIM NABUCO',
        344041.0: 'FUNDACAO CULTURAL PALMARES',
        344042.0: 'FUNDACAO BIBLIOTECA NACIONAL',
        364001.0: 'CNPQ - ADMINISTRACAO CENTRAL',
        364102.0: 'CONSELHO NAC DE DESENV CIENT E TECNOLOGICO',
        364999.0: 'CNPQ - DIFERENCIA CAMBIAL',
        365001.0: 'FINANCIADORA DE ESTUDOS E PROJETOS',
        366003.0: 'HOSPITAL NOSSA SENHORA DA CONCEICAO S/A',
        370001.0: 'DIRETORIA DE GESTAO INTERNA(CGU)',
        373001.0: 'DPTO. DE ADMINISTRACAO FINANCEIRA-DAF - INCRA',
        380010.0: 'COORD-GERAL DE ORCAM., FIN. E CONTABILIDADE',
        380910.0: 'COORD-GERAL DE ORCAMENTO, FIN. E CONT.- CGOFC',
        390001.0: 'RESERVA DE CONTINGENCIA/MEFP',
        390002.0: 'SUBSECRETARIA DE PLAN.,ORCAM.E ADMIN.SETORIAL',
        393001.0: 'AGENCIA NACIONAL DE TRANSPORTES TERRESTRES',
        393003.0: 'DEPART.NAC.INFRA ESTRUTURA TRANSPORTES.',
        395001.0: 'EMPRESA DE PLANEJAMENTO E LOGISTICA S.A - EPL',
        396001.0: 'COMPANHIA DOCAS DO RIO DE JANEIRO',
        396002.0: 'COMPANHIA DOCAS DO ESTADO DA BAHIA',
        396003.0: 'COMPANHIA DOCAS DO CEARA',
        396004.0: 'COMPANHIA DOCAS DO PARA',
        396005.0: 'COMPANHIA DOCA DO RIO GRANDE DO NORTE',
        396006.0: 'COMPANHIA DOCAS DO ESTADO DE SAO PAULO',
        399002.0: 'COMPANHIA DOCAS DO ESPIRITO SANTO',
        400042.0: 'COORD-GERAL DE ORC., FIN. E CONT.-CGOFC (MTP)',
        403101.0: 'INSTITUTO DO PATRIMONIO HIST. E ART. NACIONAL',
        403201.0: 'FUNDACAO NACIONAL DE ARTES',
        410002.0: 'COORDENACAO-GERAL DE ORCAMENTO E FINANCAS',
        410003.0: 'COORDENACAO-GERAL DE RECURSOS LOGISTICOS',
        410007.0: 'FUNDO P/O DESENV.TECNOL.DAS TELECOMUNICACOES',
        413001.0: 'AGENCIA NACIONAL DE TELECOMUNICACOES-SEDE',
        413047.0: 'FUNDO DE UNIVERS.DOS SERV.TELECOMUNICACOES',
        415001.0: 'EMPRESA BRASILEIRA DE CORREIOS E TELEGRAFOS',
        420002.0: 'COORD.GERAL DE PLAN. ORC. FIN. E CONTAB./MINC',
        423001.0: 'INSTITUTO BRASILEIRO DE MUSEUS - IBRAM',
        440002.0: 'SUBSECRET.PLANEJAM.ORCAM.E ADMINIST±SPOA(MMA)',
        440088.0: 'SETORIAL PROG.ORCAMENTARIA E FINANCEIRA-SFB',
        443003.0: 'COORDENACAO DE ORCAMENTO E FINANCAS.',
        443019.0: 'COORD. DE PLAN. ORCAMENTO E FIN./COPLAN/JBRJ',
        443032.0: 'INST.CHICO MENDES DE CONSER.DA BIODIVERSIDADE',
        443045.0: 'SETORIAL ORCAMENTARIA E FINANCEIRA DO FNMA',
        447001.0: 'SETORIAL ORCAMENTARIA E FINANCEIRA DO FNMC',
        490002.0: 'SUBSEC. DE PLANEJ., ORCAMENTO E ADMINISTRACAO',
        490003.0: 'CREDITO FUNDIARIO',
        495001.0: 'COMPANHIA DE PESQUISA DE RECURSOS MINERAIS',
        510001.0: 'COORD.GERAL DE ORCAMENTO, FINANCAS E CONTAB.',
        513001.0: 'COORDENACAO DE ORCAMENTO E FINANCAS DO FRGPS',
        530002.0: 'ORCAMENTO E FINANCAS/MDR',
        533008.0: 'FUNDO DE DESENVOLVIMENTO DA AMAZONIA',
        533009.0: 'FUNDO DE DESENVOLVIMENTO DO NORDESTE',
        533013.0: 'SUPERINTEND. DO DESENVOLVIMENTO DA AMAZONIA',
        533014.0: 'SUPERINTENDENCIA DO DESENVOLV. DO NORDESTE',
        533018.0: 'SUPERINT. DO DESENVOLVIMENTO DO CENTRO-OESTE',
        537001.0: 'FUNDO CONSTITUCIONAL DE FINANCIAM.DO NORDESTE',
        537002.0: 'FUNDO CONSTITUCIONAL FINANCIAMENTO NORTE',
        537003.0: 'FUNDO CONSTITUCIONL DO CENTRO OESTE',
        537004.0: 'FUNDO DE DESENVOLVIMENTO DO CENTRO-OESTE',
        540001.0: 'CGOFC - SETORIAL/MTUR',
        550002.0: 'SETORIAL DE ORCAMENTO E FINANCAS/MC',
        560003.0: 'SECRETARIA EXECUTIVA - MINISTERIO DAS CIDADES',
        560015.0: 'FUNDO NACIONAL DE HABIT. DE INTERESSE SOCIAL',
        673001.0: 'DIRETORIA DE FINANCAS-SISTEMA PARA O PAIS/MM',
        682010.0: 'AGENCIA NACIONAL DE TRANSPORTES AQUAVIARIOS',
        699999.0: 'FUNDO NAVAL - DIFERENCA CAMBIAL',
        773001.0: 'DIRETORIA DE FINANCAS DA MARINHA-SISTEMA-PAIS',
        773008.0: 'DIRETORIA DE FINANCAS DA MARINHA - CCCPM',
        773009.0: 'DIRETORIA DE FINANCAS DA MARINHA - AMAZUL',
        806001.0: 'SERPRO-SEDE - DEPARTAMENTO FINANCEIRO',
        810002.0: 'SETORIAL ORCAMENTARIA E FINANCEIRA - MDH',
        873001.0: 'DIRETORIA DE FINANCAS-SISTEMA PARA O PAIS/MM',
        913001.0: 'AUTORIDADE PUBLICA OLIMPICA'
    }
    
    #Reemplazamos los valores nulos por el valor correcto
    df["nombre de la unidad gestora"].fillna(df["código de la unidad gestora"].map(diccionario_unidad_gestora), inplace=True)

    # Invertimos el diccionario para mapear nombres a códigos 
    diccionario_inverso_gestora = {valor: clave for clave, valor in diccionario_unidad_gestora.items()} 
    #Básicamente cogemos el valor y la clave y lo volvemos clave -> valor y valor -> clave así podemos hacer la tarea a la inversa

    # Rellenamos los valores nulos en 'código del órgano superior' usando el nombre
    df["código de la unidad gestora"].fillna(df["nombre de la unidad gestora"].map(diccionario_inverso_gestora), inplace=True)
    
    return


